/** JSON-friendly, readonly IR contracts. Records use stable string keys. */
export type OpaqueRef<T extends string> = string & { readonly __opaqueRef?: T };
export type TypeRef = OpaqueRef<"TypeRef">;
export interface SnapshotRef { readonly modelRelease: string; readonly modelDigest: string; readonly corpusRelease: string; readonly corpusDigest: string }
export type BundleSnapshotRef = SnapshotRef;
export interface DiagnosticIR { readonly code: string; readonly message: string; readonly path?: readonly string[]; readonly severity: "error" | "warning" | "info" }
export type ValueIR = null | boolean | number | string | readonly ValueIR[] | { readonly [key: string]: ValueIR };
export interface TypeDefIR { readonly name: string; readonly version: string; readonly fields: Readonly<Record<string, TypeRef>> }
export interface RelationDefIR { readonly name: string; readonly version: string; readonly from: TypeRef; readonly to: TypeRef; readonly semantics: Readonly<Record<string, ValueIR>> }
export interface FunctionDefIR { readonly name: string; readonly version: string; readonly inputs: Readonly<Record<string, TypeRef>>; readonly output: TypeRef; readonly provider?: string }
export interface ActionDefIR { readonly name: string; readonly version: string; readonly inputs: Readonly<Record<string, TypeRef>>; readonly output: TypeRef; readonly capabilities: readonly string[]; readonly sideEffects: string }
export interface ProjectionDefIR { readonly name: string; readonly version: string; readonly targetTokens: number; readonly rules: readonly Readonly<Record<string, ValueIR>>[] }
export interface RetrievalProfileDefIR { readonly name: string; readonly version: string; readonly projectionRef: string; readonly featureWeights: Readonly<Record<string, number>> }
export interface SchemaIR { readonly protocolVersion: string; readonly model: { readonly name: string; readonly version: string; readonly digest: string }; readonly types: Readonly<Record<string, TypeDefIR>>; readonly relations: Readonly<Record<string, RelationDefIR>>; readonly functions: Readonly<Record<string, FunctionDefIR>>; readonly actions: Readonly<Record<string, ActionDefIR>>; readonly projections: Readonly<Record<string, ProjectionDefIR>>; readonly retrievalProfiles: Readonly<Record<string, RetrievalProfileDefIR>>; readonly policies?: Readonly<Record<string, ValueIR>>; readonly validators?: Readonly<Record<string, ValueIR>> }
export interface UnitIR { readonly identity: { readonly id: string; readonly version: string; readonly digest: string; readonly corpus: string }; readonly typeRef: TypeRef; readonly implements: readonly TypeRef[]; readonly fields: Readonly<Record<string, ValueIR>>; readonly relations: readonly GraphEdgeIR[]; readonly citations: readonly string[]; readonly policyLabels: readonly string[]; readonly lifecycle: "draft" | "active" | "deprecated" | "deleted"; readonly visibility: "private" | "shared" | "public"; readonly provenance: Readonly<Record<string, ValueIR>>; readonly projections: Readonly<Record<string, ValueIR>> }
export interface GraphEdgeIR { readonly id: string; readonly relationRef: string; readonly from: string; readonly to: string; readonly attributes?: Readonly<Record<string, ValueIR>> }
export interface GraphIR { readonly snapshot: SnapshotRef; readonly units: readonly UnitIR[]; readonly edges: readonly GraphEdgeIR[]; readonly diagnostics: readonly DiagnosticIR[]; readonly indexes: Readonly<Record<string, readonly string[]>> }
export interface SelectionCandidateIR { readonly unitId: string; readonly score: number; readonly featureValues: Readonly<Record<string, number>>; readonly reasons: readonly string[] }
export interface RelationExpansionIR { readonly relationRef: string; readonly from: string; readonly discovered: readonly string[]; readonly depth: number }
export interface SelectionPlanIR { readonly requestId: string; readonly snapshot: SnapshotRef; readonly query: Readonly<Record<string, ValueIR>>; readonly candidates: readonly SelectionCandidateIR[]; readonly selected: readonly SelectionCandidateIR[]; readonly rejections: readonly { readonly candidate: SelectionCandidateIR; readonly reasons: readonly string[] }[]; readonly relationExpansions: readonly RelationExpansionIR[]; readonly conflicts: readonly DiagnosticIR[]; readonly budget: { readonly maxTokens: number; readonly consumedTokens?: number }; readonly projectionLoads: readonly { readonly projectionRef: string; readonly unitIds: readonly string[] }[]; readonly unsatCore?: readonly string[]; readonly rationale?: readonly DiagnosticIR[] }
export type ExecutionPlanNodeIR = { readonly id: string; readonly kind: "Query" | "Materialize" | "InvokeAction" | "InvokeFunction" | "InvokeModel" | "Transform" | "Validate" | "Gate" | "Emit" | "AwaitApproval"; readonly target: string; readonly inputs: Readonly<Record<string, ValueIR>>; readonly dependsOn: readonly string[] };
export interface ExecutionPlanIR { readonly snapshot: SnapshotRef; readonly runId: string; readonly nodes: readonly ExecutionPlanNodeIR[]; readonly edges: readonly { readonly from: string; readonly to: string }[]; readonly capabilities: readonly string[]; readonly approvals: readonly string[]; readonly checkpoints: readonly string[]; readonly budget: { readonly maxTokens?: number; readonly maxDurationMs?: number }; readonly diagnostics?: readonly DiagnosticIR[] }
