/**
 * @module generated-artifact
 *
 * The contract between a code generator and the client that loads its output.
 *
 * Plan §14.3 requires that "所有生成物携带 model digest，运行时调用前可验证一致性".
 * The header lives on the *client* side of the dependency edge on purpose: the
 * party that must refuse to run is the client, so the client owns the check and
 * the generator merely stamps what the check reads. Putting the assertion in the
 * generator instead would leave every consumer free to skip it.
 *
 * The check is fail-closed. A missing or unparsable header is a rejection, not a
 * "generated by an older version, probably fine" — a generated SDK whose digest
 * cannot be established is indistinguishable from one generated against a
 * different model.
 */

import type { SnapshotRef } from "@skill-wiki/ir";
import { SdkError } from "./types.ts";

export const GENERATED_ARTIFACT_PROTOCOL = "prime/generated/v1";

export interface GeneratedModelRef {
  readonly name: string;
  readonly version: string;
  readonly digest: string;
}

export interface GeneratedArtifactHeader {
  readonly protocol: string;
  readonly model: GeneratedModelRef;
  /** Which generator produced the artifact, for a diagnosable mismatch. */
  readonly generator: string;
}

export class ModelDigestMismatchError extends SdkError {
  readonly expected: string;
  readonly actual: string;

  constructor(expected: string, actual: string, generator: string) {
    super(
      `Generated artifact was built against model digest ${expected} but the active snapshot carries ${actual} (generator: ${generator})`,
    );
    this.name = "ModelDigestMismatchError";
    this.expected = expected;
    this.actual = actual;
  }
}

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Narrow an untrusted value into a header. A generated file is data that arrived
 * from outside this process — it may have been edited by hand — so its shape is
 * checked rather than asserted.
 */
export function parseGeneratedArtifactHeader(value: unknown): GeneratedArtifactHeader {
  if (!isRecord(value)) throw new SdkError("Generated artifact header must be an object");
  const model = value.model;
  if (typeof value.protocol !== "string" || value.protocol.length === 0) {
    throw new SdkError("Generated artifact header is missing `protocol`");
  }
  if (typeof value.generator !== "string" || value.generator.length === 0) {
    throw new SdkError("Generated artifact header is missing `generator`");
  }
  if (!isRecord(model)) throw new SdkError("Generated artifact header is missing `model`");
  for (const key of ["name", "version", "digest"] as const) {
    if (typeof model[key] !== "string" || (model[key] as string).length === 0) {
      throw new SdkError(`Generated artifact header is missing \`model.${key}\``);
    }
  }
  return {
    protocol: value.protocol,
    generator: value.generator,
    model: { name: model.name as string, version: model.version as string, digest: model.digest as string },
  };
}

/**
 * The pre-call gate. Only `digest` and `protocol` are compared.
 *
 * `model.version` is deliberately *not* compared against `SnapshotRef.modelRelease`:
 * a release string is a publication identity that can be re-cut without the model
 * content changing, so a version comparison would reject artifacts that are
 * byte-identical in meaning while still not catching a model edited in place. The
 * digest catches exactly the case that matters and nothing else.
 */
export function assertGeneratedArtifactUsable(
  header: GeneratedArtifactHeader,
  snapshot: SnapshotRef,
): void {
  if (header.protocol !== GENERATED_ARTIFACT_PROTOCOL) {
    throw new SdkError(
      `Unsupported generated-artifact protocol '${header.protocol}'; this client supports '${GENERATED_ARTIFACT_PROTOCOL}'`,
    );
  }
  if (snapshot.modelDigest.length === 0) {
    throw new SdkError("Active snapshot carries no model digest, so a generated artifact cannot be verified");
  }
  if (header.model.digest !== snapshot.modelDigest) {
    throw new ModelDigestMismatchError(header.model.digest, snapshot.modelDigest, header.generator);
  }
}
