import { describe, expect, test } from "bun:test";
import { loadModelOrThrow, type LoadedModel } from "@aoe/model-schema";
import { ActionProviderRegistry, ActionRuntime, FunctionProviderRegistry, InMemoryEventStore } from "../src/index.ts";

const model = loadModelOrThrow(new URL("../../model-schema/test/fixtures/ticket-model", import.meta.url).pathname);
const context = { principal: "tester", roles: ["agent"], allowedCapabilities: [], budget: {}, snapshot: "snapshot-1", trace: "trace-1" };
const ticket = { title: "Fix", active: true, owner: { name: "Ada" } };
const allowed = { authorize: async () => ({ allowed: true, reason: "test allow", evidence: [{ kind: "role", value: "agent" }] }) };
function setup(execute = async () => true) { const actions = new ActionProviderRegistry().register("ticket-resolver", { execute }); const functions = new FunctionProviderRegistry().register("declarative-fixture", { invoke: async ({ ticket: value }: any) => value.title }); const events = new InMemoryEventStore(); return { runtime: new ActionRuntime(model, { actions, functions, events, authorizer: allowed }), events } }

describe("governed action runtime", () => {
  test("validates the external Ticket action and rejects unknown fields", async () => { const { runtime } = setup(); expect(await runtime.execute("ResolveTicket", { ticket }, context, "ok")).toMatchObject({ status: "succeeded", output: true }); expect(await runtime.execute("ResolveTicket", { ticket: { ...ticket, extra: 1 } }, context, "invalid")).toMatchObject({ status: "denied" }) });
  test("requires principal authorization before capability and provider execution", async () => { let calls = 0; const runtime = new ActionRuntime(model, { actions: new ActionProviderRegistry().register("ticket-resolver", { execute: async () => { calls++; return true } }) }); const run = await runtime.execute("ResolveTicket", { ticket }, context, "auth"); expect(run).toMatchObject({ status: "denied", error: "No principal authorizer" }); expect(calls).toBe(0); expect(runtime.events(run.id).map(x => x.type)).toEqual(["run.created", "authorization.decided", "authorization.denied"]) });
  test("public preflight authorizes but never calls an ActionProvider", async () => { let providers = 0, authorizations = 0; const runtime = new ActionRuntime(model, { actions: new ActionProviderRegistry().register("ticket-resolver", { execute: async () => { providers++; return true } }), authorizer: { authorize: async () => { authorizations++; return { allowed: false, reason: "denied" } } } }); await expect(runtime.preflight("ResolveTicket", { ticket }, context)).rejects.toThrow("denied"); expect(authorizations).toBe(1); expect(providers).toBe(0); const allow = new ActionRuntime(model, { actions: new ActionProviderRegistry().register("ticket-resolver", { execute: async () => { providers++; return true } }), authorizer: allowed }); expect((await allow.preflight("ResolveTicket", { ticket }, context)).authorizationDecision?.allowed).toBe(true); expect(providers).toBe(0) });
  test("denies missing capability and effectful actions without explicit capability", async () => { let calls = 0; const changed = structuredClone(model) as typeof model, action = changed.definitions.find(x => x.kind === "action") as any; action.capabilities = ["ticket:write"]; const runtime = new ActionRuntime(changed, { actions: new ActionProviderRegistry().register("ticket-resolver", { execute: async () => { calls++; return true } }), authorizer: allowed }); expect((await runtime.execute("ResolveTicket", { ticket }, context, "cap")).status).toBe("denied"); action.capabilities = []; action.sideEffects = "write"; expect((await runtime.execute("ResolveTicket", { ticket }, context, "effect")).status).toBe("denied"); expect(calls).toBe(0) });
  test("dry-run does not claim or require an idempotency key; approval has provenance", async () => { let calls = 0; const { runtime } = setup(async () => { calls++; return true }); expect((await runtime.execute("ResolveTicket", { ticket }, context, "", true)).status).toBe("planned"); expect((await runtime.execute("ResolveTicket", { ticket }, context, "dry")).status).toBe("succeeded"); const changed = structuredClone(model) as typeof model; (changed.definitions.find(x => x.kind === "action") as any).approval = "always"; const human = new ActionRuntime(changed, { actions: new ActionProviderRegistry().register("ticket-resolver", { execute: async () => { calls++; return true } }), authorizer: allowed }); const waiting = await human.execute("ResolveTicket", { ticket }, context, "human"); await expect(human.approve(waiting.id, { principal: "" })).rejects.toThrow("Approval principal is required"); expect(calls).toBe(1); expect((await human.approve(waiting.id, { principal: "reviewer", roles: ["approver"], evidence: [{ kind: "review", value: "R1" }] })).status).toBe("succeeded"); expect(calls).toBe(2); expect(human.events(waiting.id).some(event => event.type === "approval.granted" && event.payload.principal === "reviewer")).toBe(true) });
  test("canonicalizes input, shares in-flight work, and rejects invalid fingerprints", async () => { let calls = 0; const { runtime } = setup(async () => { calls++; await new Promise(resolve => setTimeout(resolve, 5)); return true }); const one = runtime.execute("ResolveTicket", { ticket: { title: "Fix", active: true, owner: { name: "Ada" } } }, context, "same"); const two = runtime.execute("ResolveTicket", { ticket: { owner: { name: "Ada" }, active: true, title: "Fix" } }, context, "same"); expect((await one).id).toBe((await two).id); expect(calls).toBe(1); await expect(runtime.execute("ResolveTicket", { ticket }, context, "")).rejects.toBeInstanceOf(Error); await expect(runtime.execute("ResolveTicket", { ticket: { ...ticket, metadata: BigInt(1) } }, context, "big")).rejects.toBeInstanceOf(Error) });
  test("uses an unambiguous multi-tenant idempotency tuple", async () => { let calls = 0; const { runtime } = setup(async () => { calls++; return true }); const left = { ...context, tenant: "a|b", workspace: "c" }, right = { ...context, tenant: "a", workspace: "b|c" }; const first = await runtime.execute("ResolveTicket", { ticket }, left, "tuple"); const second = await runtime.execute("ResolveTicket", { ticket }, right, "tuple"); expect(second.id).not.toBe(first.id); expect(second.context.principal).toBe("tester"); expect(calls).toBe(2); expect((await runtime.execute("ResolveTicket", { ticket }, left, "tuple")).id).toBe(first.id) });
  test("dry-run skips fingerprints for unknown BigInt input", async () => { let calls = 0; const { runtime } = setup(async () => { calls++; return true }); const run = await runtime.execute("ResolveTicket", { ticket: { ...ticket, metadata: BigInt(1) } }, context, "", true); expect(run.status).toBe("planned"); expect(calls).toBe(0) });
  test("retries within a bounded budget and emits ordered attempt events", async () => { let calls = 0; const { runtime } = setup(async () => { calls++; if (calls < 3) throw new Error("transient"); return true }); const run = await runtime.execute("ResolveTicket", { ticket }, { ...context, budget: { maxAttempts: 3 } }, "retry"); expect(run).toMatchObject({ status: "succeeded", attempts: 3 }); expect(calls).toBe(3); expect(runtime.events(run.id).map(x => x.type)).toEqual(["run.created", "authorization.decided", "provider.attempt.started", "provider.attempt.failed", "provider.attempt.started", "provider.attempt.failed", "provider.attempt.started", "provider.attempt.succeeded", "run.succeeded"]); const exhausted = await setup(async () => { throw new Error("nope") }).runtime.execute("ResolveTicket", { ticket }, { ...context, budget: { maxAttempts: 2 } }, "exhaust"); expect(exhausted).toMatchObject({ status: "failed", attempts: 2 }) });
  test("only idempotent definitions may retry", async () => { for (const idempotency of ["non-idempotent", "unknown"] as const) { let calls = 0; const changed = structuredClone(model) as typeof model; (changed.definitions.find(x => x.kind === "action") as any).idempotency = idempotency; const runtime = new ActionRuntime(changed, { actions: new ActionProviderRegistry().register("ticket-resolver", { execute: async () => { calls++; throw new Error("transient") } }), authorizer: allowed }); const run = await runtime.execute("ResolveTicket", { ticket }, { ...context, budget: { maxAttempts: 3 } }, idempotency); expect(run).toMatchObject({ status: "failed", attempts: 0, error: "Retries require an idempotent action definition" }); expect(calls).toBe(0) } });
  test("closes timeout and policy-error runs without late success", async () => { const { runtime } = setup(async () => new Promise(resolve => setTimeout(() => resolve(true), 20))); const timeout = await runtime.execute("ResolveTicket", { ticket }, { ...context, budget: { timeoutMs: 1 } }, "slow"); await new Promise(resolve => setTimeout(resolve, 25)); expect(timeout).toMatchObject({ status: "failed", error: "Provider timeout" }); expect(runtime.events(timeout.id).map(x => x.type)).toEqual(["run.created", "authorization.decided", "provider.attempt.started", "provider.attempt.failed", "run.failed"]); const changed = structuredClone(model) as typeof model; (changed.definitions.find(x => x.kind === "action") as any).approval = "conditional"; const policy = new ActionRuntime(changed, { actions: new ActionProviderRegistry().register("ticket-resolver", { execute: async () => true }), authorizer: allowed, policy: { decide: async () => { throw new Error("offline") } } }); const denied = await policy.execute("ResolveTicket", { ticket }, context, "policy-error"); expect(denied).toMatchObject({ status: "failed", error: "Policy provider error: offline" }); expect(policy.events(denied.id).map(x => x.type)).toEqual(["run.created", "authorization.decided", "policy.error", "policy.failed"]) });
  test("policy deny fails closed before a provider runs", async () => { let calls = 0; const changed = structuredClone(model) as typeof model; (changed.definitions.find(x => x.kind === "action") as any).approval = "conditional"; const runtime = new ActionRuntime(changed, { actions: new ActionProviderRegistry().register("ticket-resolver", { execute: async () => { calls++; return true } }), authorizer: allowed, policy: { decide: async () => ({ allowed: false, reason: "blocked" }) } }); const run = await runtime.execute("ResolveTicket", { ticket }, context, "policy-deny"); expect(run.status).toBe("denied"); expect(calls).toBe(0); expect(runtime.events(run.id).map(x => x.type)).toEqual(["run.created", "authorization.decided", "policy.decided", "policy.denied"]) });
  test("accumulates authorization and policy evidence", async () => { const changed = structuredClone(model) as typeof model; (changed.definitions.find(x => x.kind === "action") as any).approval = "conditional"; const runtime = new ActionRuntime(changed, { actions: new ActionProviderRegistry().register("ticket-resolver", { execute: async () => true }), authorizer: { authorize: async () => ({ allowed: true, reason: "auth", evidence: [{ kind: "auth", value: "A" }] }) }, policy: { decide: async () => ({ allowed: true, reason: "policy", evidence: [{ kind: "policy", value: "P" }] }) } }); const run = await runtime.execute("ResolveTicket", { ticket }, context, "evidence"); expect(run.evidence).toEqual([{ kind: "auth", value: "A" }, { kind: "policy", value: "P" }]); expect(runtime.events(run.id).find(event => event.type === "policy.decided")?.payload.evidence).toEqual([{ kind: "policy", value: "P" }]) });
  test("authorizer errors and invalid contexts fail closed with auditable terminal runs", async () => { let calls = 0, authCalls = 0; const runtime = new ActionRuntime(model, { actions: new ActionProviderRegistry().register("ticket-resolver", { execute: async () => { calls++; return true } }), authorizer: { authorize: async () => { authCalls++; throw new Error("offline") } } }); const error = await runtime.execute("ResolveTicket", { ticket }, context, "auth-error"); expect(error).toMatchObject({ status: "denied", authorizationDecision: { allowed: false, reason: "Authorization provider error: offline" }, evidence: [{ kind: "authorization-error", value: "offline" }] }); expect(runtime.events(error.id).map(x => x.type)).toEqual(["run.created", "authorization.error", "authorization.denied"]); const invalid = await runtime.execute("ResolveTicket", { ticket }, { ...context, snapshot: "" }, "invalid-context"); expect(invalid.status).toBe("denied"); expect(authCalls).toBe(1); expect(calls).toBe(0) });
  test("functions fail closed and a distinct Document model has no Ticket branch", async () => { let actionCalls = 0; const { runtime } = setup(async () => { actionCalls++; return true }); expect(await runtime.invokeFunction("TicketSummary", { ticket }, context)).toMatchObject({ output: "Fix" }); expect(actionCalls).toBe(0); expect(await runtime.invokeFunction("TicketSummary", { ticket: { title: 2 } }, context)).toHaveProperty("error"); const documentModel: LoadedModel = { root: "/model", manifest: { protocol: "prime/model/v2", name: "documents", version: "1.0.0", files: ["definitions.yaml"] }, definitions: [{ kind: "type", name: "Document", version: "1.0.0", fields: [{ name: "id", typeRef: "string", required: true }], additionalFields: "reject" }, { kind: "action", name: "ArchiveDocument", version: "1.0.0", inputs: [{ name: "document", typeRef: "Document", required: true }], output: "boolean", capabilities: [], sideEffects: "none", idempotency: "idempotent", approval: "never", provider: "archive" }] }; const documents = new ActionRuntime(documentModel, { actions: new ActionProviderRegistry().register("archive", { execute: async () => true }), authorizer: allowed }); expect((await documents.execute("ArchiveDocument", { document: { id: "d-1" } }, context, "doc")).status).toBe("succeeded") });
});
