/**
 * @module emit-typescript
 *
 * `CodegenSchema` -> TypeScript. Two files come out of here:
 *
 *  - `types.ts`: one `interface` per declared type, one input/output alias per
 *    action and function, and the `GeneratedArtifactHeader` that §14.3's runtime
 *    gate reads. The header is typed as `GeneratedArtifactHeader` rather than as an
 *    anonymous object literal so that a drift between what the generator stamps and
 *    what the client verifies is a *compile* error in the generated file, not a
 *    runtime surprise on the day someone regenerates.
 *  - `client.ts`: the §10.3 typed model SDK — one accessor per declared action, each
 *    carrying the model's own input and output types, over `PrimeClient`.
 *
 * There is no domain name in this module. Every identifier it writes is derived
 * from a name that arrived in the schema.
 */

import type { SchemaIR } from "@skill-wiki/ir";
import { GENERATED_ARTIFACT_PROTOCOL } from "@skill-wiki/sdk";
import { camelCase, pascalCase, uniqueIdentifiers } from "./identifiers.ts";
import { isBuiltinTypeRef, parseTypeRef, type CodegenSchema, type DeclaredField } from "./schema-ir.ts";

export const GENERATOR_ID = "@skill-wiki/sdk-codegen";

const HEADER_COMMENT = [
  "// GENERATED by " + GENERATOR_ID + " — do not edit.",
  "//",
  "// Regenerate from the Model Package instead. This file is bound to one model",
  "// digest: `GENERATED_MODEL` below is what the runtime gate compares before a call.",
  "",
].join("\n");

/**
 * Builtin refs map to TS primitives; anything else is a declared type. `unknown`,
 * `*` and `generic*` all become `unknown` rather than `any`: `any` would silently
 * disable the checking the generated SDK exists to provide, and the model said
 * "unconstrained", not "unchecked".
 */
/**
 * Wrap in `readonly T[]` once per array level. `readonly` rather than `T[]` because
 * every generated member is `readonly`, and a mutable array behind a readonly
 * property is a hole in exactly that promise. Anything that is not a bare
 * identifier gets parenthesised, so `readonly (readonly T[])[]` and
 * `readonly ("a" | "b")[]` both parse as written.
 */
function arrayOf(inner: string, depth: number): string {
  let out = inner;
  for (let level = 0; level < depth; level += 1) {
    out = `readonly ${/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(out) ? out : `(${out})`}[]`;
  }
  return out;
}

function tsType(ref: string, typeNames: ReadonlyMap<string, string>): string {
  const parsed = parseTypeRef(ref);
  // `model-schema.validateLinks` already rejects a malformed or dangling ref, so
  // reaching here means the schema was assembled by something that skipped it.
  if (parsed === undefined) throw new Error(`Malformed type reference '${ref}'`);
  return arrayOf(elementTsType(parsed.element, typeNames), parsed.arrayDepth);
}

function elementTsType(ref: string, typeNames: ReadonlyMap<string, string>): string {
  switch (ref) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    default:
      break;
  }
  if (isBuiltinTypeRef(ref)) return "unknown";
  const declared = typeNames.get(ref);
  if (declared === undefined) {
    throw new Error(`Type reference '${ref}' is neither a builtin nor a declared type in this schema`);
  }
  return declared;
}

/**
 * A field's TypeScript type. A declared value set becomes a literal union, which is
 * the whole point of declaring one: `motion_priority: "low" | "med" | "high"` makes a
 * wrong value a compile error in the generated SDK, where `string` made it a runtime
 * surprise. Parenthesised inside an array so `("a" | "b")[]` does not parse as
 * `"a" | ("b"[])`.
 */
function fieldTsType(field: DeclaredField, typeNames: ReadonlyMap<string, string>): string {
  const values = field.enumValues;
  if (values === undefined || values.length === 0) return tsType(field.typeRef, typeNames);
  const parsed = parseTypeRef(field.typeRef);
  if (parsed === undefined) throw new Error(`Malformed type reference '${field.typeRef}'`);
  return arrayOf(values.map(value => JSON.stringify(value)).join(" | "), parsed.arrayDepth);
}

function docComment(text: string | undefined, indent: string): string {
  return text === undefined ? "" : `${indent}/** ${text.replace(/\*\//g, "*\\/")} */\n`;
}

/** Quote a property name only when it is not a plain identifier, so the output reads like hand-written TS. */
function propertyName(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function fieldLines(fields: readonly DeclaredField[], typeNames: ReadonlyMap<string, string>): string {
  if (fields.length === 0) {
    return "  // The Model Package declares no field on this shape.\n  readonly [key: string]: never;\n";
  }
  return fields
    .map(field => {
      const optional = field.required ? "" : "?";
      return `${docComment(field.description, "  ")}  readonly ${propertyName(field.name)}${optional}: ${fieldTsType(field, typeNames)};`;
    })
    .join("\n") + "\n";
}

export interface TypeScriptNames {
  readonly types: ReadonlyMap<string, string>;
  readonly actions: ReadonlyMap<string, string>;
  readonly functions: ReadonlyMap<string, string>;
  readonly actionMethods: ReadonlyMap<string, string>;
  readonly modelClass: string;
}

export function typeScriptNames(schema: SchemaIR): TypeScriptNames {
  return {
    types: uniqueIdentifiers(Object.keys(schema.types), pascalCase, "Type"),
    actions: uniqueIdentifiers(Object.keys(schema.actions), pascalCase, "Action"),
    functions: uniqueIdentifiers(Object.keys(schema.functions), pascalCase, "Function"),
    actionMethods: uniqueIdentifiers(Object.keys(schema.actions), camelCase, "Action"),
    modelClass: `${pascalCase(schema.model.name)}Model`,
  };
}

export function emitTypes(input: CodegenSchema, names: TypeScriptNames): string {
  const { schema } = input;
  const out: string[] = [HEADER_COMMENT];
  out.push(`import type { GeneratedArtifactHeader } from "@skill-wiki/sdk";`, "");
  out.push(
    "/** The §14.3 stamp. Verify it against the activated snapshot before any call. */",
    "export const GENERATED_MODEL: GeneratedArtifactHeader = {",
    `  protocol: ${JSON.stringify(GENERATED_ARTIFACT_PROTOCOL)},`,
    `  generator: ${JSON.stringify(GENERATOR_ID)},`,
    "  model: {",
    `    name: ${JSON.stringify(schema.model.name)},`,
    `    version: ${JSON.stringify(schema.model.version)},`,
    `    digest: ${JSON.stringify(schema.model.digest)},`,
    "  },",
    "};",
    "",
  );

  for (const [modelName, identifier] of names.types) {
    const fields = input.typeFields[modelName] ?? [];
    out.push(
      `/** Declared type \`${modelName}\` v${schema.types[modelName]!.version}. */`,
      `export interface ${identifier} {`,
      fieldLines(fields, names.types).replace(/\n$/, ""),
      "}",
      "",
    );
  }

  for (const [modelName, identifier] of names.actions) {
    const action = schema.actions[modelName]!;
    const inputs = input.actionInputs[modelName] ?? [];
    out.push(
      `/** Input of action \`${modelName}\` (sideEffects: ${action.sideEffects}). */`,
      `export interface ${identifier}Input {`,
      fieldLines(inputs, names.types).replace(/\n$/, ""),
      "}",
      `export type ${identifier}Output = ${tsType(action.output, names.types)};`,
      "",
    );
  }

  for (const [modelName, identifier] of names.functions) {
    const fn = schema.functions[modelName]!;
    const inputs = input.functionInputs[modelName] ?? [];
    out.push(
      `/** Input of function \`${modelName}\`. */`,
      `export interface ${identifier}Input {`,
      fieldLines(inputs, names.types).replace(/\n$/, ""),
      "}",
      `export type ${identifier}Output = ${tsType(fn.output, names.types)};`,
      "",
    );
  }

  out.push(
    "/** Accessor name -> the model's own action name, so a caller never spells one by hand. */",
    "export const ACTION_NAMES = {",
    ...[...names.actionMethods].map(([modelName, accessor]) => `  ${accessor}: ${JSON.stringify(modelName)},`),
    "} as const;",
    "",
  );
  return out.join("\n");
}

export function emitClient(input: CodegenSchema, names: TypeScriptNames): string {
  const { schema } = input;
  const out: string[] = [HEADER_COMMENT];
  const typeImports = [...names.actions.values()].flatMap(identifier => [`${identifier}Input`, `${identifier}Output`]);
  out.push(
    `import type { ActionRun, PrimeClient, RequestContext } from "@skill-wiki/sdk";`,
    `import { GENERATED_MODEL${typeImports.length > 0 ? ", " : ""}${typeImports.join(", ")} } from "./types.ts";`,
    "",
  );
  out.push(
    "/**",
    ` * Typed façade over \`PrimeClient\` for model \`${schema.model.name}\` v${schema.model.version}.`,
    " *",
    " * `verify()` is separate from the constructor because the digest gate needs the",
    " * activated snapshot, which is an async question the constructor cannot ask.",
    " */",
    `export class ${names.modelClass} {`,
    "  constructor(private readonly prime: PrimeClient) {}",
    "",
    "  /** Fail closed if this generated SDK does not match the engine's active model. */",
    "  async verify(): Promise<void> {",
    "    await this.prime.verifyGeneratedArtifact(GENERATED_MODEL);",
    "  }",
    "",
  );
  for (const [modelName, accessor] of names.actionMethods) {
    const identifier = names.actions.get(modelName)!;
    const traits = input.actionTraits[modelName]!;
    out.push(
      `  /** Action \`${modelName}\` — sideEffects: ${traits.sideEffects}, idempotency: ${traits.idempotency}, approval: ${traits.approval}. */`,
      `  async ${accessor}(`,
      `    input: ${identifier}Input,`,
      "    context: RequestContext,",
      "    idempotencyKey: string,",
      "  ): Promise<ActionRun> {",
      `    return this.prime.execute({ action: ${JSON.stringify(modelName)}, input, context, idempotencyKey });`,
      "  }",
      "",
    );
  }
  out.push("}", "");
  // A model may declare no action at all (`compat/prime-v1-model` declares none),
  // and `export type { } from ...` would be a valid but confusing artifact.
  if (typeImports.length > 0) out.push(`export type { ${typeImports.join(", ")} } from "./types.ts";`, "");
  return out.join("\n");
}
