import { afterEach, describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { loadModel, loadModelOrThrow, ModelLoadError, ModelManifestSchema, TypeDefinitionSchema } from "../src/index.ts";
const compat = join(import.meta.dir, "../../../compat/prime-v1-model"); const ticket = join(import.meta.dir, "fixtures/ticket-model"); const roots: string[] = [];
const codes = (root: string) => { const r = loadModel(root); return r.ok ? [] : r.diagnostics.map(d => d.code); };
function fixture(manifest: string, files: Record<string, string>): string { const root = mkdtempSync(join(tmpdir(), "model-schema-")); roots.push(root); writeFileSync(join(root, "prime-model.yaml"), manifest); for (const [file, content] of Object.entries(files)) writeFileSync(join(root, file), content); return root; }
afterEach(() => { while (roots.length) rmSync(roots.pop()!, { recursive: true, force: true }); });
describe("external model loader", () => {
  test("loads compat model with chunker groups and projection fields", () => { const r = loadModel(compat); expect(r.ok).toBe(true); if (!r.ok) return; const ds = r.value.definitions; expect(ds.filter(d => d.kind === "type")).toHaveLength(28); const rs = ds.filter(d => d.kind === "relation"); expect(rs).toHaveLength(14); expect(rs.map(d => d.name)).toEqual(["related","compatible","conflicts","see-also","extends","derived-from","requires","enhances","validates-with","supplies-to","specializes","contradicts","relationships","includes"]); const core = ds.find(d => d.kind === "projection" && d.name === "core"); if (!core || core.kind !== "projection") throw new Error("core missing"); expect(core.typeGroups).toEqual({data:["fact","term","value","category","example","counter-example","source","metric"],behaviour:["step","check","transform","tool"],composition:["method","rule","taxonomy","pattern","anti-pattern","type"],"style-meta":["persona","voice","constraint","template","provocation","collection","scope","tradeoff","principle","feedback"]}); expect(core.rules[0]?.include).toEqual(expect.arrayContaining(["facts","definitions","categories","checks","steps"])); expect(core.exclude).toContain("sources"); const full = ds.find(d => d.kind === "projection" && d.name === "full"); expect(full?.kind === "projection" && full.include).toContain("provenance"); });
  test("matches legacy link directions and conflicts", () => { const r = loadModel(compat); if (!r.ok) throw new Error("compat failed"); const rel = (name: string) => r.value.definitions.find(d => d.kind === "relation" && d.name === name); const order = (name: string) => { const x = rel(name); return x?.kind === "relation" ? x.semantics.loadOrder : undefined; }; const aliases = (name: string) => { const x = rel(name); return x?.kind === "relation" ? x.aliases : undefined; }; expect(order("requires")).toBe("before"); expect(order("enhances")).toBe("none"); expect(order("validates-with")).toBe("after"); expect(order("supplies-to")).toBe("after"); expect(order("specializes")).toBe("none"); const conflicts = rel("conflicts"); const contradicts = rel("contradicts"); expect(conflicts?.kind === "relation" && conflicts.semantics.selection).toBe("exclude"); expect(contradicts?.kind === "relation" && contradicts.semantics.conflictSeverity).toBe("error"); expect(aliases("see-also")).toEqual(["see_also"]); expect(aliases("derived-from")).toEqual(["derived_from"]); expect(aliases("validates-with")).toEqual(["validates_with"]); expect(aliases("supplies-to")).toEqual(["supplies_to"]); });
  test("reports duplicate and dangling diagnostics", () => { const duplicate = fixture("protocol: prime/model/v2\nname: x\nversion: 1.0.0\nfiles: [d.yaml, d.yaml]\n", {"d.yaml":"kind: definitions\nversion: 1.0.0\ndefinitions: [{kind: type, name: X, version: 1.0.0}, {kind: type, name: X, version: 1.0.0}]\n"}); expect(codes(duplicate)).toEqual(expect.arrayContaining(["DUPLICATE_FILE_PATH", "DUPLICATE_DEFINITION"])); const dangling = fixture("protocol: prime/model/v2\nname: x\nversion: 1.0.0\nfiles: [d.yaml]\n", {"d.yaml":"kind: definitions\nversion: 1.0.0\ndefinitions: [{kind: type, name: X, version: 1.0.0, fields: [{name: y, typeRef: Missing}]}]\n"}); expect(codes(dangling)).toContain("DANGLING_TYPE_REF"); });
  test("rejects invalid strict semver", () => { const m = fixture("protocol: prime/model/v2\nname: x\nversion: 1.0.0-01\nfiles: [d.yaml]\n", {"d.yaml":"kind: definitions\nversion: 1.0.0\ndefinitions: [{kind: type, name: X, version: 1.0.0}]\n"}); expect(codes(m)).toContain("INVALID_MANIFEST"); const d = fixture("protocol: prime/model/v2\nname: x\nversion: 1.0.0\nfiles: [d.yaml]\n", {"d.yaml":"kind: definitions\nversion: 1.0.0\ndefinitions: [{kind: type, name: X, version: 1.0.0-01}]\n"}); expect(codes(d)).toContain("INVALID_DEFINITION_FILE"); });
  test("accepts build metadata but rejects numeric prerelease zeroes", () => { const base = {protocol: "prime/model/v2", name: "x", files: ["d.yaml"]}; expect(ModelManifestSchema.safeParse({...base, version: "1.0.0-01"}).success).toBe(false); expect(ModelManifestSchema.safeParse({...base, version: "1.0.0+abc-01"}).success).toBe(true); expect(ModelManifestSchema.safeParse({...base, version: "1.0.0-alpha.01+build"}).success).toBe(false); });
  test("rejects dangling projection group members", () => { const root = fixture("protocol: prime/model/v2\nname: x\nversion: 1.0.0\nfiles: [d.yaml]\n", {"d.yaml":"kind: definitions\nversion: 1.0.0\ndefinitions: [{kind: projection, name: p, version: 1.0.0, targetTokens: 1, typeGroups: {x: [Missing]}}]\n"}); expect(codes(root)).toContain("DANGLING_TYPE_REF"); });
  test("rejects unknown projection group rule", () => { const root = fixture("protocol: prime/model/v2\nname: x\nversion: 1.0.0\nfiles: [d.yaml]\n", {"d.yaml":"kind: definitions\nversion: 1.0.0\ndefinitions: [{kind: type, name: X, version: 1.0.0}, {kind: projection, name: p, version: 1.0.0, targetTokens: 1, rules: [{typeRef: group:no-such-group}]}]\n"}); expect(codes(root)).toContain("DANGLING_TYPE_GROUP_REF"); });
  test("loads standalone ticket fixture", () => { const r = loadModel(ticket); expect(r.ok).toBe(true); if (r.ok) expect(r.value.definitions.map(d => d.name)).toEqual(["Note","Ticket","Owner","owned-by","TicketSummary","ResolveTicket","summary","core","full"]); });
  test("rejects traversal and manifest symlink escapes", () => { const root = fixture("protocol: prime/model/v2\nname: x\nversion: 1.0.0\nfiles: [../x]\n", {}); expect(codes(root)).toContain("PATH_OUTSIDE_ROOT"); const outside = fixture("protocol: prime/model/v2\nname: x\nversion: 1.0.0\nfiles: [d.yaml]\n", {"d.yaml":"kind: definitions\nversion: 1.0.0\ndefinitions: [{kind: type, name: X, version: 1.0.0}]\n"}); const linked = mkdtempSync(join(tmpdir(), "model-schema-link-")); roots.push(linked); symlinkSync(join(outside, "prime-model.yaml"), join(linked, "prime-model.yaml")); expect(codes(linked)).toContain("PATH_OUTSIDE_ROOT"); });
  test("throws diagnostics-bearing error", () => { const root = fixture("protocol: prime/model/v2\nname: x\nversion: 1.0.0\nfiles: [../x]\n", {}); expect(() => loadModelOrThrow(root)).toThrow(ModelLoadError); });
  test("rejects a missing model root without throwing", () => { expect(codes(join(tmpdir(), "no-such-model-root")).includes("MODEL_ROOT_INVALID")).toBe(true); });
  // A corpus-attested kind can close its schema because its field set was measured exhaustively;
  // an unattested kind cannot, because `reject` there would be an invented contract. See
  // docs/lanes/L2-COMPAT-FIELDS.md for the per-kind evidence.
  test("closes the schema of every corpus-attested type and leaves unattested types open", () => { expect(TypeDefinitionSchema.parse({kind:"type",name:"Closed",version:"1.0.0"}).additionalFields).toBe("reject"); const r=loadModel(compat); if(!r.ok) throw new Error("compat failed"); const types=r.value.definitions.filter((d): d is Extract<typeof d, {kind:"type"}> => d.kind==="type"); const closed=types.filter(d=>d.additionalFields==="reject").map(d=>d.name).sort(); expect(closed).toEqual(["anti-pattern","collection","fact","method","pattern","principle","rule","term","tradeoff"]); expect(types.filter(d=>d.additionalFields==="unknown")).toHaveLength(19); });
});
